<?
$permissions = array(
  'Admin' => array(
    'edit_everyone_schedule' => true,
    'add_installation' => true,
    'view_material_delivery' => true,
    'view_tickets' => true,
    'view_tasks' => true,
    'view_shop' => true,
    'view_notes' => true,
    'edit_notes' => true,'add_notes' => true,
    'delete_notes' => true,
    'show_pricing' => true,
    'view_client' => true,
    'edit_client' => true,
    'add_client' => true,
    'delete_client' => true,
    'view_requests' => true,
    'edit_requests' => true,
    'delete_requests' => true,
    'add_requests' => true,
    'view_quotes' => true,
    'add_quotes' => true,
    'delete_quotes' => true,
    'edit_quotes' => true,
    'view_jobs' => true,
    'add_jobs' => true,
    'edit_jobs' => true,
    'delete_jobs' => true,
    'view_invoices' => true,
    'add_invoices' => true,
    'edit_invoices' => true,
    'delete_invoices' => true,    
  ),
  'Client' => array(
    'view_requests' => true,
    'view_quotes' => true,
    'view_invoices' => true,
  ),
  'Crew Supervisor' => array(
    'view_tickets' => true,
    'view_tasks' => true,
    'view_shop' => true,
    'view_material_delivery' => true,
    'edit_everyone_schedule' => true,
    'view_notes' => true,
    'edit_notes' => true,'add_notes' => true,
    'show_pricing' => true,
    'view_client' => true,
    'edit_client' => true,
    'add_client' => true,
    'view_requests' => true,
    'edit_requests' => true,
    'add_requests' => true,
    'view_quotes' => true,
    'view_jobs' => true,
    'add_jobs' => true,
    'edit_jobs' => true,
    'view_invoices' => true    
  ),
  'Installation Crew' => array(
    'view_tickets' => false,
    'view_own_schedule' => true,
    'view_notes' => true,
    'edit_notes' => true,'add_notes' => true,
    'view_jobs' => true,
    'add_installation' => true,
    'edit_installation' => true,
  ),
  'Shop Manager' => array(
    'view_tasks' => true,
    'view_shop' => true,
    'edit_everyone_schedule' => true,
    'view_notes' => true,
    'edit_notes' => true,'add_notes' => true,
    'view_client' => true,
    'edit_client' => true,
    'add_client' => true,
    'view_requests' => true,
    'edit_requests' => true,
    'add_requests' => true,
    'view_quotes' => true,
    'view_jobs' => true,
    'add_jobs' => true,
    'edit_jobs' => true,
  ),
  'Drafting' => array(
    'edit_everyone_schedule' => true,
    'view_notes' => true,
    'edit_notes' => true,'add_notes' => true,
    'view_client' => true,
    'edit_client' => true,
    'add_client' => true,
    'view_requests' => true,
    'edit_requests' => true,
    'add_requests' => true,
    'view_quotes' => true,
    'add_quotes' => true,
    'edit_quotes' => true,
    'view_jobs' => true,
    'add_jobs' => true,
    'edit_jobs' => true,
    'view_invoices' => true,
  ),
  'Estimator' => array(
    'view_tickets' => true,
    'view_tasks' => true,
    'view_shop' => true,
    'view_material_delivery' => true,
    'view_own_schedule' => true,
    'view_notes' => true,
    'edit_notes' => true,'add_notes' => true,
    'view_client' => true,
    'edit_client' => true,
    'add_client' => true,
    'view_requests' => true,
    'add_requests' => true,
    'view_quotes' => true,
    'add_quotes' => true,
    'edit_quotes' => true,
    'view_jobs' => true,
    'view_invoices' => true,
    'view_analytics' => true,
  ),
  'Material Drafter' => array(
    'view_tasks' => true,
    'view_shop' => true,
    'view_material_delivery' => true,
    'edit_everyone_schedule' => true,
    'view_notes' => true,
    'edit_notes' => true,'add_notes' => true,
    'delete_notes' => true,
    'view_client' => true,
    'edit_client' => true,
    'add_client' => true,
    'view_requests' => true,
    'add_requests' => true,
    'edit_requests' => true,
    'view_quotes' => true,
    'add_quotes' => true,
    'edit_quotes' => true,
    'view_jobs' => true,
    'add_jobs' => true,
    'edit_jobs' => true,
    'view_invoices' => true,
    'add_invoices' => true,
    'edit_invoices' => true,
  ),
  'Customer Service' => array(
    'view_tickets' => true,
    'view_tasks' => true,
    'view_shop' => true,
    'view_material_delivery' => true,
    'edit_everyone_schedule' => true,
    'view_notes' => true,
    'edit_notes' => true,'add_notes' => true,
    'view_client' => true,
    'edit_client' => true,
    'add_client' => true,
    'view_requests' => true,
    'add_requests' => true,
    'edit_requests' => true,
    'view_quotes' => true,
    'add_quotes' => true,
    'edit_quotes' => true,
    'view_jobs' => true,
    'add_jobs' => true,
    'edit_jobs' => true,
    'view_invoices' => true,
    'add_invoices' => true,
    'edit_invoices' => true,
  ),
);
?>